openapi: 3.0.3
info:
  title: To-Do Checklist Storage API
  version: "1.0.0"
  description: Stores checklist events in a database (events are consumed from Kafka). Only supports GET queries via HTTP.

paths:
  /health:
    get:
      summary: Health check
      operationId: app.health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /stats:
    get:
      summary: gets the event stats
      operationId: app.get_event_stats
      responses:
        '200':
          description: sucessfully returned the storage stats
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Stats"
  /todo/checklist-items:
    get:
      summary: Get checklist item events by timespan
      operationId: app.get_checklist_item_events
      description: Returns checklist item events stored between start_timestamp (>=) and end_timestamp (<)
      parameters:
        - name: start_timestamp
          in: query
          required: true
          schema:
            type: string
            format: date-time
            
        - name: end_timestamp
          in: query
          required: true
          schema:
            type: string
            format: date-time
           
      responses:
        '200':
          description: Successfully returned checklist item events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistItemEvent'
        '400':
          description: invalid input

  /todo/checklist-summaries:
    get:
      summary: Get checklist summary events by timespan
      operationId: app.get_checklist_summary_events
      description: Returns checklist summary events stored between start_timestamp (>=) and end_timestamp (<)
      parameters:
        - name: start_timestamp
          in: query
          required: true
          schema:
            type: string
            format: date-time
            
        - name: end_timestamp
          in: query
          required: true
          schema:
            type: string
            format: date-time
            
      responses:
        '200':
          description: Successfully returned checklist summary events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistSummaryEvent'
        '400':
          description: invalid input

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: Storage is healthy
    Stats:
      type: object
      required:
        - num_temp
        - num_precip
      properties:
        num_temp:
          type: integer
          example: 100
        num_precip:
          type: integer
          example: 100

    ChecklistItemEvent:
      type: object
      required:
        - trace_id
        - sender_id
        - sent_timestamp
        - list_name
        - item_name
        - completed
        - completed_at
        - estimated_mins
      properties:
        trace_id:
          type: string
          
        sender_id:
          type: string
          
        sent_timestamp:
          type: string
          
        list_name:
          type: string
          
        item_name:
          type: string
          
        completed:
          type: boolean
          
        completed_at:
          type: string
          format: date-time
          
        estimated_mins:
          type: integer
          

    ChecklistSummaryEvent:
      type: object
      required:
        - trace_id
        - sender_id
        - sent_timestamp
        - list_name
        - items_completed
        - items_total
        - summary_at
      properties:
        trace_id:
          type: string
          
        sender_id:
          type: string
          
        sent_timestamp:
          type: string
          format: date-time
          
        list_name:
          type: string
          
        items_completed:
          type: integer
          
        items_total:
          type: integer
          
        summary_at:
          type: string
          format: date-time
          
