version: 1

datastore:
  filename: /data/health.sqlite

scheduler:
  period_sec: 5
  timeout_sec: 5

services: #L12
  receiver:
    url: http://receiver:8080/receiver/health
  storage:
    url: http://storage:8090/storage/health
  processing:
    url: http://processing:8100/processing/health
  analyzer:
    url: http://analyzer:8110/analyzer/health