version: 1

datastore:
  filename: /data/data.json

scheduler:
  period_sec: 5

eventstores:
  checklist_items:
    url: http://storage:8090/todo/checklist-items
  checklist_summaries:
    url: http://storage:8090/todo/checklist-summaries
